## Design Environment (schema-compliant example)
# Converted from earlier free-form example to align with environment-manifest.schema.yaml
# Some illustrative fields (gpu, per-container mounts) omitted until schema evolves.

apiVersion: gateos.ultracube.v1alpha1
kind: Environment
metadata:
  name: design
  description: "Creative workstation: 3D + raster + vector + media preview"
spec:
  profile:
    category: design
  containers:
    - name: blender
      image: ghcr.io/library/blender:latest
      resources:
        cpu: "2"
        memory: 4Gi
    - name: gimp
      image: ghcr.io/linuxcontainers/gimp:latest
    - name: krita
      image: ghcr.io/linuxcontainers/krita:latest
    - name: asset-export
      image: ghcr.io/ultra-cube/gateos-asset-exporter:latest
  env:
    - name: GATEOS_ENV
      value: design
  security:
    isolationLevel: balanced
