name: Dev Check & Coverage Badge

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  dev-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run consolidated dev check
        run: |
          chmod +x scripts/dev-check.sh
          ./scripts/dev-check.sh
      - name: Generate coverage badge
        if: success()
        run: |
          coverage-badge -o coverage.svg -f
      - name: Commit coverage badge
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [[ -n $(git status --porcelain coverage.svg) ]]; then
            git add coverage.svg
            git commit -m "chore: update coverage badge"
            git push
          fi